# Generated by Django 2.1.2 on 2018-11-03 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentContent', models.TextField()),
                ('commentBy', models.CharField(max_length=30)),
                ('commentDate', models.DateTimeField()),
                ('commentNumberOfLikes', models.IntegerField()),
                ('commentNumberOfVotes', models.IntegerField()),
                ('commentNumberOfFlags', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postedBy', models.CharField(max_length=30)),
                ('postTitle', models.CharField(max_length=80)),
                ('postTopic', models.CharField(max_length=30)),
                ('postContent', models.TextField()),
                ('postDate', models.DateTimeField()),
                ('postNumberOfLikes', models.IntegerField()),
                ('postNumberOfVotes', models.IntegerField()),
                ('postNumberOfFlags', models.IntegerField()),
                ('postNumberOfReplies', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='commentOnPost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
    ]
