# Generated by Django 2.1.2 on 2018-11-03 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postNumberOfReplies',
            new_name='postNumberOfComments',
        ),
    ]
