# Generated by Django 2.1.4 on 2019-03-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postAutoClassification',
            field=models.BooleanField(default=False),
        ),
    ]
