# Generated by Django 2.1.2 on 2018-11-03 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='replyNumberOfVotes',
        ),
    ]
