# Generated by Django 2.1.2 on 2018-11-10 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20181110_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-commentNumberOfVotes']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-postNumberOfVotes', '-postDate']},
        ),
        migrations.AddField(
            model_name='comment',
            name='commentImage',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='postImage',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
