# Generated by Django 2.1.2 on 2018-11-12 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.UserProfile'),
        ),
    ]
