# Generated by Django 2.1.2 on 2018-11-21 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_reply_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='likes',
            new_name='commentLikes',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='likes',
            new_name='postLikes',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='likes',
            new_name='replyLikes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='commentNumberOfLikes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='postNumberOfLikes',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='replyNumberOfLikes',
        ),
    ]
