# Generated by Django 2.1.2 on 2018-11-21 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0016_auto_20181121_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentVotes',
            field=models.ManyToManyField(blank=True, related_name='comment_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
