# Generated by Django 2.1.2 on 2018-11-21 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0017_comment_commentvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postVotes',
            field=models.ManyToManyField(blank=True, related_name='post_votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
