# Generated by Django 2.1.2 on 2018-11-21 19:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0018_post_postvotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postVotes',
        ),
        migrations.AddField(
            model_name='post',
            name='postVotersDown',
            field=models.ManyToManyField(blank=True, related_name='post_votes_down', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='postVotersUp',
            field=models.ManyToManyField(blank=True, related_name='post_votes_up', to=settings.AUTH_USER_MODEL),
        ),
    ]
