# Generated by Django 2.1.2 on 2018-11-21 19:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0019_auto_20181121_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commentVotes',
        ),
        migrations.AddField(
            model_name='comment',
            name='commentVotersDown',
            field=models.ManyToManyField(blank=True, related_name='comment_votes_down', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='commentVotersUp',
            field=models.ManyToManyField(blank=True, related_name='comment_votes_up', to=settings.AUTH_USER_MODEL),
        ),
    ]
