# Generated by Django 2.1.2 on 2018-11-21 20:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0020_auto_20181121_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentFlags',
            field=models.ManyToManyField(blank=True, related_name='comment_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='postFlags',
            field=models.ManyToManyField(blank=True, related_name='post_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='replyFlags',
            field=models.ManyToManyField(blank=True, related_name='reply_flags', to=settings.AUTH_USER_MODEL),
        ),
    ]
