# Generated by Django 2.1.2 on 2018-11-21 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_auto_20181121_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commentNumberOfFlags',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='replyNumberOfFlags',
        ),
    ]
