# Generated by Django 2.1.2 on 2018-11-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0022_auto_20181121_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentDisabled',
            field=models.BooleanField(default=False),
        ),
    ]
