# Generated by Django 2.1.2 on 2018-11-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0023_comment_commentdisabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postDisabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reply',
            name='replyDisabled',
            field=models.BooleanField(default=False),
        ),
    ]
