# Generated by Django 2.1.2 on 2018-11-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0024_auto_20181122_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='replyBy',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='replyFlags',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='replyLikes',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='replytoComment',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
