# Generated by Django 2.1.2 on 2018-11-24 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0025_auto_20181124_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
