# Generated by Django 2.1.2 on 2018-12-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0027_auto_20181126_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postlastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
