# Generated by Django 2.1.2 on 2018-12-08 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0028_post_postlastupdated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postlastUpdated',
            new_name='postLastUpdated',
        ),
    ]
