# Generated by Django 2.1.2 on 2018-12-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0029_auto_20181208_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postClosed',
            field=models.BooleanField(default=False),
        ),
    ]
