# Generated by Django 2.1.2 on 2019-02-12 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replyContent', models.TextField(verbose_name='Reply to Comment:')),
                ('replyDate', models.DateTimeField(auto_now_add=True)),
                ('replyDisabled', models.BooleanField(default=False)),
                ('replyBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UserProfile')),
                ('replyFlags', models.ManyToManyField(blank=True, related_name='reply_flags', to='main.UserProfile')),
                ('replyLikes', models.ManyToManyField(blank=True, related_name='reply_likes', to='main.UserProfile')),
                ('replytoComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.Comment')),
            ],
        ),
    ]
