# Generated by Django 2.1.2 on 2018-11-26 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='replyBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UserProfile'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='replyFlags',
            field=models.ManyToManyField(blank=True, related_name='reply_flags', to='main.UserProfile'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='replyLikes',
            field=models.ManyToManyField(blank=True, related_name='reply_likes', to='main.UserProfile'),
        ),
    ]
