# Generated by Django 2.1.2 on 2019-02-12 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='num_of_posts_comments_replies',
            new_name='numOfPostsCommentsReplies',
        ),
    ]
