# Generated by Django 2.1.2 on 2018-11-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='num_of_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='num_of_posts_comments_replies',
            field=models.IntegerField(default=0),
        ),
    ]
