# Generated by Django 2.1.2 on 2019-02-12 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190212_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='num_of_likes',
            new_name='numberOfLikes',
        ),
    ]
