# Generated by Django 2.1.2 on 2019-02-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190212_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='activation_code',
            new_name='activationCode',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='reset_password_code',
            new_name='resetPasswordCode',
        ),
    ]
