# Generated by Django 2.1.2 on 2019-02-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190212_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='date_joined',
            new_name='dateJoined',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_picture',
            new_name='profilePicture',
        ),
    ]
