# Generated by Django 2.1.2 on 2018-11-24 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0025_auto_20181124_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentContent', models.TextField()),
                ('commentImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('commentDate', models.DateTimeField(auto_now_add=True)),
                ('commentNumberOfVotes', models.IntegerField(default=0)),
                ('commentDisabled', models.BooleanField(default=False)),
                ('commentBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('commentFlags', models.ManyToManyField(blank=True, related_name='comment_flags', to=settings.AUTH_USER_MODEL)),
                ('commentLikes', models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
                ('commentOnPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
                ('commentVotersDown', models.ManyToManyField(blank=True, related_name='comment_votes_down', to=settings.AUTH_USER_MODEL)),
                ('commentVotersUp', models.ManyToManyField(blank=True, related_name='comment_votes_up', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-commentNumberOfVotes'],
            },
        ),
    ]
