# Generated by Django 2.1.2 on 2018-11-26 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commentBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UserProfile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentFlags',
            field=models.ManyToManyField(blank=True, related_name='comment_flags', to='main.UserProfile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentLikes',
            field=models.ManyToManyField(blank=True, related_name='comment_likes', to='main.UserProfile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentVotersDown',
            field=models.ManyToManyField(blank=True, related_name='comment_votes_down', to='main.UserProfile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commentVotersUp',
            field=models.ManyToManyField(blank=True, related_name='comment_votes_up', to='main.UserProfile'),
        ),
    ]
