# Generated by Django 2.1.2 on 2018-12-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20181126_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentLastUpdated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
