# Generated by Django 2.1.2 on 2018-12-08 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_comment_commentlastupdated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commentLastUpdated',
        ),
    ]
