# Generated by Django 2.1.2 on 2018-12-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_remove_comment_commentlastupdated'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commentAccepted',
            field=models.BooleanField(default=False),
        ),
    ]
